package main

import (
	"fmt"
	"os"
	"sort"

	_ "github.com/delahondes/gowiki/core"
	"github.com/delahondes/gowiki/docmodel"
)

func main() {
	out := os.Stdout

	fmt.Fprintln(out, "// Code generated by gen-nodespec; DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, `export type Flow = "inline" | "block"`)
	fmt.Fprintln(out, `export const FLOW_INLINE: Flow = "inline"`)
	fmt.Fprintln(out, `export const FLOW_BLOCK: Flow = "block"`)
	fmt.Fprintln(out)
	fmt.Fprintln(out, "export type NodeSpec = {")
	fmt.Fprintln(out, "  kind: string")
	fmt.Fprintln(out, "  flow: Flow")
	fmt.Fprintln(out, "  childrenFlow?: Flow")
	fmt.Fprintln(out, "  allowedChildren?: readonly string[]")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "export const NODE_SPECS: readonly NodeSpec[] = [")

	// Deterministic order (important)
	kinds := make([]string, 0, len(getNodeSpecs()))
	for k := range getNodeSpecs() {
		kinds = append(kinds, string(k))
	}
	sort.Strings(kinds)

	for _, k := range kinds {
		spec := getNodeSpecs()[docmodel.Kind(k)]
		emitNodeSpec(out, spec)
	}

	fmt.Fprintln(out, "] as const")
}

func emitNodeSpec(out *os.File, spec docmodel.NodeSpec) {
	fmt.Fprintln(out, "  {")
	fmt.Fprintf(out, "    kind: %q,\n", spec.Kind)
	fmt.Fprintf(out, "    flow: %q,\n", flowToString(spec.Flow))

	if spec.ChildrenFlow != nil {
		fmt.Fprintf(out, "    childrenFlow: %q,\n", flowToString(*spec.ChildrenFlow))
	}

	if len(spec.AllowedChildren) > 0 {
		fmt.Fprint(out, "    allowedChildren: [")
		for i, k := range spec.AllowedChildren {
			if i > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, "%q", k)
		}
		fmt.Fprintln(out, "],")
	}

	fmt.Fprintln(out, "  },")
}

func flowToString(f docmodel.Flow) string {
	switch f {
	case docmodel.FlowInline:
		return "inline"
	case docmodel.FlowBlock:
		return "block"
	default:
		panic("unknown Flow")
	}
}

// Accessor to keep main clean and allow future refactors
func getNodeSpecs() map[docmodel.Kind]docmodel.NodeSpec {
	// You already have this registry; this just centralizes access
	return docmodel.AllNodeSpecs()
}
